name: Trigger auto deployment for tic-tac-toe-fe

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/tic-tac-toe-fe-AutoDeployTrigger-e1735956-04a4-4581-8134-2efb7583548e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TICTACTOEFE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TICTACTOEFE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TICTACTOEFE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: hub.docker.com
          registryUsername: ${{ secrets.TICTACTOEFE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TICTACTOEFE_REGISTRY_PASSWORD }}
          containerAppName: tic-tac-toe-fe
          resourceGroup: tic-tac-toe
          imageToBuild: hub.docker.com/tic-tac-toe-fe:${{ github.sha }}
          


