name: Trigger auto deployment for tic-tac-toe-fe

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/tic-tac-toe-fe-AutoDeployTrigger-429f7331-aa33-401d-b23e-0b4de298975b.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TICTACTOEFE_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.TICTACTOEFE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TICTACTOEFE_REGISTRY_PASSWORD }}
          containerAppName: tic-tac-toe-fe
          resourceGroup: tic-tac-toe
          imageToBuild: harshith8854/tic-tac-toe-fe:${{ github.sha }}
          

     

